os: osx
language: node_js
node_js:
  - stable
before_install:
  - npm i npm@^4 -g
  - mkdir www
install:
  - npm install -g npm
before_script:
  - npm install -g ionic cordova; cordova platform add ios
  - npm install @ionic/app-scripts@latest
  - npm install localforage
  - rm -rf node_modules/@types/localforage
script:
  - ionic cordova build ios --release
