matrix:
  include:
    - language: android
      install: ant deps
      android:
      components:
        - tools
        - platform-tools
        - build-tools-28.0.3
        - android-26
        - add-on
        - extra
    - language: node_js
      node_js: 
        - stable
      before_install:
        - npm install -g npm
        - mkdir www
      install:
        - npm install
      before_script:
        - npm install -g ionic cordova; cordova platform add android
        - npm install @ionic/app-scripts@latest
        - npm install localforage
        - rm -rf node_modules/@types/localforage
      script:
        - ionic cordova build browser android --release  
notifications:
  email:
    - laurentiu.raducu@gmail.com
