language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
before_install:
  - sudo apt-get install nodejs
  - sudo apt-get install nodejs npm
  - mkdir www
  - npm config set strict-ssl false
  - sudo npm i npm@^4 -g
install:
  - sudo npm install -g npm
before_script:
  - sudo npm install -g ionic cordova; cordova platform add android
  - sudo cordova platform rm android
  - sudo cordova platform add android
  - sudo npm install @ionic/app-scripts@latest
  - sudo npm install localforage
  - sudo rm -rf node_modules/@types/localforage
script:
  - ionic cordova build android --release
