language: android
sudo: required
jdk: oraclejdk8
android:
    components:
        - tools
        - platform-tools
        - build-tools-26.0.2
        - android-26
        - android-22
        - android-24
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-26
        - sys-img-armeabi-v7a-android-22
        - sys-img-armeabi-v7a-android-24
      before_install:
        - npm install -g npm
        - mkdir www
      install:
        - npm install
      before_script:
        - npm install -g ionic cordova; cordova platform add android
        - npm install @ionic/app-scripts@latest
        - npm install localforage
        - rm -rf node_modules/@types/localforage
      script:
        - ionic cordova build browser android --release  
notifications:
  email:
    - laurentiu.raducu@gmail.com
