os: osx
language: node_js
      node_js: 
        - stable
      before_install:
        - npm install -g npm
        - mkdir www
      install:
        - npm install -g npm
      before_script:
        - npm install -g ionic cordova; cordova platform add ios
        - npm install @ionic/app-scripts@latest
        - rm -rf node_modules/@types/localforage
      script:
        - ionic cordova build browser ios --release  
notifications:
  email:
    - laurentiu.raducu@gmail.com
