language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
before_install:
  - sudo apt-get install nodejs
  - sudo apt-get install nodejs npm
  - mkdir www
  - npm config set strict-ssl false
install:
  - npm install -g npm
before_script:
  - npm install -g ionic cordova; cordova platform add android
  - cordova platform rm android
  - cordova platform add android
  - npm install @ionic/app-scripts@latest
  - npm install localforage
  - rm -rf node_modules/@types/localforage
script:
  - ionic cordova build android --release
