language: node_js
node_js:
  - stable
before_install:
  - npm i npm@^4 -g
  - mkdir www
install:
  - npm install -g npm
before_script:
  - npm install -g ionic cordova; cordova platform add android
  - npm install @ionic/app-scripts@latest
script:
  - ionic cordova build browser android prod
