jobs:
  include:
    - stage: build app on ios
      os: osx
      language: node_js
      node_js:
        - stable
      before_install:
        - rm package-lock.json
        - npm i npm@^4 -g
        - mkdir www
      install:
        - npm install -g npm
      before_script:
        - npm cache clean -f
        - npm install ionic@4.10.4 --loglevel verbose
        - npm install cordova@6.0.0
        - cordova platform add ios
        - npm install @ionic/app-scripts@latest
        - npm install localforage
        - rm -rf node_modules/@types/localforage
      script:
        - ionic cordova build ios --release
      notifications:
        email:
          - laurentiu.raducu@gmail.com
    - stage: build app on android
      os: linux
      language: node_js
      node_js:
        - stable
      addons:
        firefox: "66.0"
        apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
            - g++-4.8
            - openjdk-7-jdk
            - lib32stdc++6
            - lib32z1
      env:
        CXX=g++-4.8
  
      before_install:
        - npm i npm@^4 -g
        - mkdir www
  
      install:
        - npm install -g npm
        - npm install -g ionic 
        - npm install cordova@8.0.0 
        - cordova platform add android
        - npm install @ionic/app-scripts@latest
        - npm install localforage
        - rm -rf node_modules/@types/localforage

      before_script:
        - wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
        - tar -xf android-sdk_r24.4-linux.tgz
        - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
        - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-26.0.2
        - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-26
        - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-27
        - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
        - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
        - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
        - export ANDROID_HOME=$PWD/android-sdk-linux
        - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/26.0.2
        
      script:
        - ionic cordova build android --release
      after_success:
        - bash $HOME/build/GrepDev/kitchen-mobile/prepare-apk.sh
        - sudo apt-get install xauth
        - npm install -g protractor
        - cd $HOME
        - npm install geckodriver
        - webdriver-manager update
        - webdriver-manager start &
        - sleep 10
        - cd $HOME/build/GrepDev/kitchen-mobile/
        - ionic serve &
        - sleep 300
        - cd $HOME/build/GrepDev/kitchen-mobile/src/protractor
        - protractor conf.js

      deploy:
        provider: releases
        api_key: $GITHUB_API_KEY
        file: /home/travis/build/GrepDev/kitchen-mobile/platforms/android/app/build/outputs/apk/release/edesia.apk
        skip_cleanup: true
        on:
          tags: false
      notifications:
        email:
          - oalexoprea@yahoo.com
          - laurentiu.raducu@gmail.com
