language: android
android:
  components:
     - platform-tools
     - tools
     - build-tools-28.0.3
     - android-28
     - extra-android-m2repository
     - extra-android-support
     - extra-google-m2repository
     - extra-google-google_play_services
env:
  global:
    - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
    - PATH=${ANDROID_HOME}/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}
language: node_js
node_js:
  - stable
before_install:
  - npm i npm@^4 -g
  - mkdir www
install:
  - npm install -g npm
before_script:
  - npm install -g ionic cordova; cordova platform add android
  - cordova platform rm android
  - cordova platform add android
  - npm install @ionic/app-scripts@latest
  - npm install localforage
  - rm -rf node_modules/@types/localforage
  - cordova requirements
script:
  - ionic cordova build android --release
