language: android
android:
  components:
     - platform-tools
     - tools
     - build-tools-28.0.3
     - android-28
     - extra-android-m2repository
     - extra-android-support
     - extra-google-m2repository
     - extra-google-google_play_services
language: node_js
node_js:
  - stable
before_install:
  - npm i npm@^4 -g
  - mkdir www
install:
  - npm install -g npm
before_script:
  - export ANDROID_HOME=~/android-sdk-linux 
  - export PATH=$PATH:$ANDROID_HOME/tools 
  - export PATH=$PATH:$ANDROID_HOME/platform-tools  
  - npm install -g ionic cordova; cordova platform add android
  - cordova platform rm android
  - cordova platform add android
  - npm install @ionic/app-scripts@latest
  - npm install localforage
  - rm -rf node_modules/@types/localforage
  - cordova requirements
  - android list sdk --all
  - android update sdk -u -a -t 19
  - android update sdk -u -a -t 20
script:
  - ionic cordova build android --release
